### ISSUE TITLE
[feature request] Notch for eatch Item

### ISSUE THREAD

**Issue by gbdomubpkm** [matdahl/einkaufszettel#13]
Hello.
First, thank you for this app.

Yes we can currently remove each item from a list if necessary but I suggest that you provide a notch for each item: will be used to indicate that each item was found in store. This notch can be checked or unchecked as required.

**Comment by matdahl** [comment]
Thanks for the idea!

In v1.3.1 there is now a possibility to check/uncheck entries in the list to mark them e.g. as "in my cart" without deleting them.

**Comment by gbdomubpkm** [comment]
Thank you
