### ISSUE TITLE
[feature request] Deleting categories

### ISSUE THREAD

**Issue by gbdomubpkm** [matdahl/einkaufszettel#16]
Implement a way to select and delete all the categories we want at once or at least, a global category removal button

**Comment by matdahl** [comment]
good point. I think, in the next step I'll unify the deleting options for all list panels in the app and implement a "delete all selected items" feature in addition to the "delete all".

**Comment by matdahl** [comment]
this is implemented in v1.3.2

**Comment by gbdomubpkm** [comment]
Thanks
